### ISSUE TITLE
URL参数改了，怎么还是提示无效URL

### ISSUE THREAD

**Issue by doutuo** [lzher/LJWX#1]
URL参数改了，怎么还是提示无效URL
getQueryVariable("https://www.baidu.com")

**Comment by lzher** [comment]
不需要修改源代码，请把这个html文件部署在公网上，访问时通过通过GET设置url参数即可。下面是一个例子。

假设您将仓库中的 `index.html` 部署在 https://example.com 中，想要绕过wx验证访问的的网站是 https://www.baidu.com ，这时需要访问以下网址：

```https://example.com/index.html?url=https://www.baidu.com```

请注意url参数的位置。

**Comment by doutuo** [comment]
大佬 ，新版微信安卓 的，貌似不能跳转了哟

**Comment by lzher** [comment]
> 大佬 ，新版微信安卓 的，貌似不能跳转了哟

在微信内，正常的逻辑应该是提示需要在浏览器打开，并附上跳转链接以供复制访问，而非自动跳转。

在外部浏览器中，正常的逻辑才是进行自动的跳转。
